eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  sleuth:
    sampler:
      probability: 1.0F

server:
  port: 8781


feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
  hystrix:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"


#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#	      thread:
#	        timeoutInMilliseconds: 1000
#product-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule