eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-service
server:
  port: 8781


feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000


#product-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule