

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true


spring:
  application:
    name: product-service
  sleuth:
    sampler:
      probability: 1.0F

server:
  port: 8771


